image: node:16.15.1

pages:
  stage: deploy
  before_script:
    - npm install
  script:
    - NODE_ENV=production npm run build
    - mv dist/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
